st-universe/core

src/html/options.xhtml

Tabellenzeile Accounteinstellung über volle Breie #3

---

src/Module/Colony/Action/BeamFrom/BeamFrom.php

Fix error message when beaming to a full storage

---

src/Module/Ship/Action/LoadWarpcore/LoadWarpcore.php

Hiermit sollte der Warpkern wieder (hoffentlich) wie damals auch Dilithium benötigen um geladen zu werden. Das Verhältnis zwischen Deuterium/Antimaterie/Dilithium habe ich erstmal auf 2/2/1 gesetzt.

changed WKloader to Deut/AM/Dil 2/2/1

---

src/Module/Colony/Action/ManageOrbitalShips/ManageOrbitalShips.php

WK über Kolonien laden sollte jetzt auch 2 Deut, 2 AM, und 1 Dili pro Ladung verbrauchen

update colo WK loader with dili

---

src/html/sitemacros.xhtml

Revert "gameversion referenz to changelog"

---

src/html/shipmacros.xhtml

Revert "make it possible to swtich easy from ship to ship"

---

src/html/shipmacros.xhtml

Revert "debug shipswitch in nbs"

---

src/Orm/Repository/TradeTransferRepository.php

Revert "reset transfercapacity after 24h"

---

src/Orm/Entity/Ship.php
src/html/ship.xhtml

Revert "[BUGFIX] starsystem link only when discovered"

---

src/PlanetGenerator/PlanetGenerator/PlanetGenerator.php
src/PlanetGenerator/PlanetGenerator/coldata/217.php

Revert "update x"

---

src/Public/static/css/stu.css

Revert "update colo field deact"

---

src/Public/static/css/stu.css

Revert "update cfa"

---

src/Orm/Entity/Colony.php

Revert "crewlimit min 2"

---

src/Module/Alliance/Action/PromotePlayer/PromotePlayer.php
src/html/shipmacros.xhtml

[Fixed] Issue #266
[Changed] (nbslist) Ship link only for owners
[Add] (nbslist) Ship img are linked

[Fixed] Issue #266 [Changed] (nbslist) Ship link only for owners [Add] (nbslist) Ship img are linked

---

src/Orm/Entity/Ship.php
src/Orm/Entity/ShipInterface.php
src/html/orbitalmanagement.xhtml

Revert "use correct method"

---

config.dist.json
src/Module/Colony/Lib/BuildingAction.php
src/Module/Colony/View/ShowBuilding/ShowBuilding.php
src/Module/Control/GameController.php
src/Module/Control/GameControllerInterface.php
src/Module/Index/Action/ResetPassword/ResetPassword.php
src/Module/Index/Action/SendPassword/SendPassword.php
src/Orm/Entity/User.php
src/Orm/Entity/UserInterface.php
src/Orm/Repository/CrewRepository.php
src/Public/admin/index.php
src/Public/api.php
src/Public/static/js/colony.js
src/html/admin/ajaxwindow.xhtml
src/html/admin/mapeditor_overview.xhtml
src/html/admin/mapeditor_section.xhtml
src/html/admin/playerlist.xhtml
src/html/colonymacros.xhtml

- Error message with crew overview (colony) fixed.
- Password reset mail fixed.
- Building activation text modified.
- Shows how often the building can be built.

Fixed a few minor issues, Add Buildable counter, Admin area fix 

---

src/html/userprofile.xhtml

Revert "bugfix"

---

src/Orm/Entity/Colony.php
src/Orm/Entity/Ship.php

Revert "Waren bei Beam-Anzeige sortieren"

---

src/Orm/Entity/Colony.php
src/Orm/Entity/Ship.php

Revert "'feature/beam waren sortieren'"

---

src/Orm/Entity/ShipRump.php
src/Orm/Entity/ShipRumpInterface.php
src/html/modulescreen.xhtml

Revert "Beam-Faktor zum Datenmodell hinzugefügt"

---

src/Orm/Entity/ShipRump.php
src/Orm/Entity/ShipRumpInterface.php
src/html/modulescreen.xhtml

Revert "'feature/beam factor'"

---

config.dist.json

Revert "aktivate log"

---

src/Config/ErrorHandler.php
src/Module/Control/GameController.php

Revert "Debug mode aktivieren"

---

src/html/orbitalmanagement.xhtml

Revert "'feature/ship links in orb mngmnt'"

---

src/Module/Ship/View/ShowShip/ShowShip.php
src/Orm/Repository/DatabaseEntryRepository.php
src/Orm/Repository/DatabaseEntryRepositoryInterface.php
src/html/ship.xhtml

Revert "'bugfix/issue 352 system link schiffs hud'"

---

src/Config/ErrorHandler.php

Revert "PrettyExceptions for user 126"

---

src/Module/Control/GameController.php

Revert "testweise einer Spieler-ID Fehler-Infos geben"

---

src/Module/Control/GameController.php

Revert "last try"

---

src/Config/ErrorHandler.php
src/Module/Control/GameController.php

Revert "Revert "Debug mode aktivieren""

---

src/Config/ErrorHandler.php
src/Module/Control/GameController.php

Revert "Revert "Revert "Debug mode aktivieren"""

---

src/Config/ErrorHandler.php
src/Module/Control/GameController.php

Revert "Revert "Revert "Revert "Debug mode aktivieren""""

---

src/Module/Colony/Action/BeamFrom/BeamFrom.php
src/Module/Colony/Action/BeamTo/BeamTo.php
src/Module/PlayerSetting/Action/ActivateVacation/ActivateVacation.php
src/Module/PlayerSetting/services.php
src/Module/Tick/Colony/ColonyTickManager.php
src/Module/Tick/Ship/ShipTickManager.php
src/Orm/Entity/Ship.php
src/Orm/Entity/User.php
src/Orm/Entity/UserInterface.php
src/html/options.xhtml

Revert "Revert "Implemented Vacation Mode""

---

src/Module/Ship/Action/UnloadBattery/UnloadBattery.php
src/html/ship.xhtml

Revert "fleet action for battery unload"

---

src/Module/Ship/Action/UnloadBattery/UnloadBattery.php
src/html/ship.xhtml

Revert "Feature/use fleet ebat"

---

src/Module/Ship/Action/ActivateTractorBeam/ActivateTractorBeam.php
src/Module/Ship/Lib/ShipMoverV2.php

Revert "correct var name"

---

src/Component/Ship/System/Exception/AlreadyOffException.php
src/Component/Ship/System/Exception/SystemNotActivableException.php
src/Component/Ship/System/Exception/SystemNotDeactivableException.php
src/Component/Ship/System/ShipSystemManager.php
src/Component/Ship/System/ShipSystemModeEnum.php
src/Component/Ship/System/ShipSystemTypeEnum.php
src/Component/Ship/System/ShipSystemTypeInterface.php
src/Component/Ship/System/Type/AbstractShipSystemType.php
src/Component/Ship/System/Type/CloakShipSystem.php
src/Component/Ship/System/Type/EnergyWeaponShipSystem.php
src/Component/Ship/System/Type/LongRangeScannerShipSystem.php
src/Component/Ship/System/Type/ProjectileWeaponShipSystem.php
src/Component/Ship/System/Type/ShieldShipSystem.php
src/Component/Ship/System/Type/TomatoPeelerShipSystem.php
src/Component/Ship/System/Type/WarpdriveShipSystem.php
src/Component/Ship/services.php
src/Lib/ModuleRumpWrapper/ModuleRumpWrapperSpecial.php
src/Module/Ship/Lib/ShipCreator.php
src/Module/ShipModule/ModuleSpecialAbilityEnum.php
src/Orm/Entity/Ship.php
src/Orm/Entity/ShipInterface.php
src/Orm/Entity/ShipSystem.php
src/Orm/Entity/ShipSystemInterface.php
src/html/ship.xhtml
src/html/shipmacros.xhtml

Revert "Revert "Feature/tomato peeler""

---

src/Orm/Entity/ShipSystem.php
src/Orm/Entity/ShipSystemInterface.php

Revert "add system_mode to ShipSystem"

---

src/Component/Ship/System/ShipSystemTypeEnum.php
src/Component/Ship/System/Type/TomatoPeelerShipSystem.php
src/Component/Ship/System/Type/WarpdriveShipSystem.php
src/Component/Ship/services.php
src/Module/Ship/Lib/ShipCreator.php
src/Module/ShipModule/ModuleSpecialAbilityEnum.php
src/html/ship.xhtml

Revert "Tachyon Scanner and Warpdrive fix"

---

src/Module/Ship/Action/ActivateShields/ActivateShields.php

Revert "dirty stuff"

---

src/Module/Colony/Action/DisassembleShip/DisassembleShip.php
src/Module/Ship/Lib/FleetNfsItem.php
src/Module/Ship/View/ShowShip/ShowShip.php
src/Orm/Repository/ShipRepository.php
src/Orm/Repository/ShipRepositoryInterface.php
src/Orm/Repository/TachyonScanRepository.php
src/Orm/Repository/TachyonScanRepositoryInterface.php
src/html/ship.xhtml

Revert "ask for active tachyon scans"

---

src/Module/Colony/Action/DisassembleShip/DisassembleShip.php
src/Module/Ship/Lib/FleetNfsItem.php
src/Module/Ship/View/ShowShip/ShowShip.php
src/Orm/Repository/ShipRepository.php
src/Orm/Repository/ShipRepositoryInterface.php
src/Orm/Repository/TachyonScanRepository.php
src/Orm/Repository/TachyonScanRepositoryInterface.php
src/html/ship.xhtml

Revert "Feature/tachyon active"

---

src/Component/Ship/System/Type/TachyonScannerShipSystem.php
src/Lib/VisualNavPanel.php
src/Lib/VisualNavPanelEntry.php
src/Module/Ship/Action/DoTachyonScan/DoTachyonScan.php
src/Module/Ship/View/ShowShip/ShowShip.php

Revert "cloaked ships in lss"

---

src/Component/Ship/System/Type/TachyonScannerShipSystem.php
src/Lib/VisualNavPanelEntry.php
src/Module/Ship/Action/DoTachyonScan/DoTachyonScan.php

Revert "radius = 2 and eps check"

---

src/Component/Ship/System/Type/TractorBeamShipSystem.php
src/Component/Ship/System/Type/WarpdriveShipSystem.php
src/Module/Ship/Action/ActivateTractorBeam/ActivateTractorBeam.php
src/Module/Ship/Action/DeactivateTractorBeam/DeactivateTractorBeam.php
src/Module/Ship/Action/EnterStarSystem/EnterStarSystem.php
src/Module/Ship/Action/LeaveStarSystem/LeaveStarSystem.php
src/Module/Ship/Lib/ShipMover.php
src/Orm/Entity/Ship.php
src/Orm/Entity/ShipInterface.php
src/html/ship.xhtml

Revert "Feature/traktor rework"

---

src/Module/Ship/Lib/ShipLeaver.php
src/Module/Tick/Ship/ShipTickManager.php
src/Orm/Repository/ShipRepository.php
src/Orm/Repository/ShipRepositoryInterface.php

Revert "remove empty escape pods"

---

src/Component/Ship/System/Type/TractorBeamShipSystem.php
src/Component/Ship/System/Type/WarpdriveShipSystem.php
src/Module/Ship/Action/ActivateTractorBeam/ActivateTractorBeam.php
src/Module/Ship/Action/DeactivateTractorBeam/DeactivateTractorBeam.php
src/Module/Ship/Action/EnterStarSystem/EnterStarSystem.php
src/Module/Ship/Action/LeaveStarSystem/LeaveStarSystem.php
src/Module/Ship/Lib/ShipMover.php
src/Orm/Entity/Ship.php
src/Orm/Entity/ShipInterface.php
src/html/ship.xhtml

Revert "add tractor ship relation"

---

src/Module/Admin/View/Map/ShowMapOverall.php

Revert "Revert "bugfix""

---

src/Module/Admin/View/Map/ShowMapOverall.php

Revert "relative path for assets"

---

src/Lib/VisualNavPanelEntry.php
src/html/ship.xhtml

Revert "show warning sign instead ?"

---

src/Module/Ship/Action/AttackShip/AttackShip.php

Revert "immediately remove escape pod trumfield"

---

src/Module/Colony/Action/DisassembleShip/DisassembleShip.php
src/Orm/Entity/ShipSystem.php
src/Orm/Entity/ShipSystemInterface.php

Revert "recycle 50% of intact modules"

---

src/Public/static/js/colony.js
src/html/modulescreen.xhtml

Revert "calculate real crew vs max crew"

---

src/Public/static/js/colony.js
src/html/modulescreen.xhtml

Revert "show crew sum based on module crew"

---

src/Public/static/js/colony.js
src/html/modulescreen.xhtml

Revert "Revert "show crew sum based on module crew""

---

src/Public/static/js/colony.js
src/html/modulescreen.xhtml

Revert "Revert "calculate real crew vs max crew""

---

src/Public/static/js/colony.js
src/html/modulescreen.xhtml

Revert "Revert "Revert "calculate real crew vs max crew"""

---

src/Public/static/js/colony.js
src/html/modulescreen.xhtml

Revert "Revert "Revert "show crew sum based on module crew"""

---

src/Public/static/js/colony.js
src/html/modulescreen.xhtml

Revert "Revert "Revert "Revert "show crew sum based on module crew""""

---

src/Public/static/js/colony.js
src/html/modulescreen.xhtml

Revert "Revert "Revert "Revert "calculate real crew vs max crew""""

---

src/Component/Crew/CrewEnum.php
src/Module/Colony/Action/BuildShip/BuildShip.php
src/Module/Crew/Lib/CrewCreator.php
src/Orm/Entity/ShipBuildplan.php
src/Orm/Entity/ShipBuildplanInterface.php
src/Orm/Entity/ShipRump.php
src/Orm/Entity/ShipRumpInterface.php
src/Public/admin/help/createBuildplan.php
src/Public/static/js/colony.js
src/admin/help/createBuildplan.php
src/html/modulescreen.xhtml

Revert "crew count based on installed modules"

---

src/Module/Crew/Lib/CrewCreator.php
src/Module/Tick/Ship/ShipTick.php
src/Orm/Repository/ShipRepository.php

Revert "Bugfix/pods start 5"

---

src/Orm/Repository/MapRepository.php

Revert "fix map field sorting"

---

src/Orm/Repository/MapRepository.php

Revert "Revert "fix map field sorting""

---

src/Config/Bootstrap.php

Revert "killing me softly"

---

src/Module/Ship/Lib/ShipMover.php
src/Orm/Repository/ModuleRepository.php

Revert "module selector sorting and flight bug"

---

src/Module/Ship/Lib/ShipMover.php
src/Orm/Repository/ModuleRepository.php

Revert "Bugfixes/divers 5"

---

src/Module/Colony/Action/DisassembleShip/DisassembleShip.php
src/Orm/Entity/ShipSystem.php
src/Orm/Entity/ShipSystemInterface.php

Revert "Feature/recycle ship modules"

---

src/Module/Colony/Action/BuildShip/BuildShip.php
src/Public/static/js/colony.js
src/html/modulescreen.xhtml

Revert "Bugfix/use buildplan"

---

src/Orm/Entity/PlanetField.php
src/Orm/Entity/Terraforming.php
src/Orm/Entity/TerraformingInterface.php
src/Orm/Repository/ShipRepository.php
src/Orm/Repository/TerraformingRepository.php
src/Orm/Repository/TerraformingRepositoryInterface.php
src/html/colonymacros.xhtml

Revert "Feature/terraforming by research 2"

---

src/Module/Maindesk/View/Overview/Overview.php
src/html/maindesk.xhtml

Revert "show crew usage on homescreen"

---

src/Module/Alliance/Action/CreatePost/CreatePost.php

Revert "update last post on topic"

---

src/html/sitemacros.xhtml

Revert "update"

---

src/Component/Ship/ShipEnum.php
src/Module/Ship/Lib/ShipMover.php
src/Orm/Entity/FlightSignature.php
src/Orm/Entity/FlightSignatureInterface.php
src/Orm/Entity/Map.php
src/Orm/Entity/StarSystemMap.php
src/Orm/Repository/services.php

Revert "Feature/flight signatures 2"

---

src/Orm/Entity/FlightSignature.php
src/Orm/Entity/FlightSignatureInterface.php

Revert "new fields cloaked and ship name"

---

src/Orm/Entity/FlightSignature.php
src/Orm/Entity/FlightSignatureInterface.php

Revert "new columns cloaked und ship name"

---

src/Orm/Entity/FlightSignature.php

Revert "new column ship name"

---

src/html/colonylist.xhtml

Revert "import colony.js"

---

src/Public/static/js/colony.js
src/html/colonylist.xhtml

Revert "added colony id as param"

---

src/Public/static/js/colony.js
src/html/colonylist.xhtml

Revert "Revert "added colony id as param""

---

src/Orm/Repository/ShipRepository.php

Revert "max two days"

---

src/html/colonymacros.xhtml

Revert "preselect"

---

src/html/ship.xhtml
src/html/shiplist.xhtml

Revert "Feature/fleet state"

---

src/Module/Trade/Action/TakeOffer/TakeOffer.php

Revert "tradestation message"

---

src/Module/Starmap/Lib/ExploreableStarMap.php
src/Module/Starmap/Lib/ExploreableStarMapInterface.php
src/Orm/Repository/MapRepository.php
src/html/starmap_section.xhtml

Revert "show mapped star systems in sector map"

---

src/Orm/Entity/ShipRump.php
src/Orm/Entity/ShipRumpInterface.php
src/html/databasemacros.xhtml

Revert "ship rump list shows fraction and rump image"

---

src/Module/Colony/Action/StartAirfieldShip/StartAirfieldShip.php

Revert "Bugfix/airfield start"

---

src/html/sitemacros.xhtml

Revert "stations seite"

---

src/html/sitemacros.xhtml

Revert "links"

---

src/html/sitemacros.xhtml

Revert "Revert "stations seite""

---

src/html/sitemacros.xhtml

Revert "Revert "Revert "stations seite"""

---

src/Module/Tick/Colony/ColonyTick.php
src/Orm/Entity/Colony.php

Revert "i dont like gagh"

---

src/Module/Ship/View/ShowScan/ShowScan.php
src/Module/Tick/Ship/ShipTick.php
src/Orm/Entity/Ship.php
src/Orm/Repository/ShipRepository.php

Revert "more indices on ship table"

---

src/Module/Tick/Ship/ShipTickManager.php

Revert "disable some ship tick functions"

---

src/Module/Tick/Colony/ColonyTickManager.php

Revert "destroy colo tick"

---

config.dist.json
src/Config/Bootstrap.php

Revert "redis faster on socket"

---

config.dist.json
src/Config/Bootstrap.php

Revert "Revert "redis faster on socket""

---

config.dist.json
src/Config/Bootstrap.php

Revert "Revert "Revert "redis faster on socket"""

---

src/Orm/Entity/Ship.php

Revert "always load ship systems to prevent postloading"

---

src/Orm/Entity/Ship.php

Revert "Revert "always load ship systems to prevent postloading""

---

src/Module/Colony/Lib/ColonySurface.php

Revert "fix"

---

src/Public/static/css/stu.css

Revert "hover"

---

composer.json
composer.lock

Also remove the deprecated zendframework/mail dependency which is the predecessor of laminas/mail

Update laminas/mail dependency

---

src/Config/Bootstrap.php
src/Config/services.php
src/Module/Maintenance/services.php

Instead of polluting the Bootstrap.php with all the base DI definitions, extract them into a single service file.
Also simplify the definition loading mechanismn.

Move base DI definition

---

phpstan-baseline.neon
src/Module/Ship/Lib/Movement/Component/FlightSignatureCreator.php
src/Module/Ship/Lib/Movement/Component/FlightSignatureCreatorInterface.php
src/Module/Ship/Lib/Movement/ShipMovementComponentsFactory.php
src/Module/Ship/Lib/Movement/ShipMovementComponentsFactoryInterface.php
src/Module/Ship/Lib/ShipMover.php
src/Orm/Repository/FlightSignatureRepository.php
src/Orm/Repository/FlightSignatureRepositoryInterface.php
tests/Module/Ship/Lib/Movement/Component/FlightSignatureCreatorTest.php
tests/Module/Ship/Lib/Movement/ShipMovementComponentsFactoryTest.php
tests/Orm/Repository/FlightSignatureRepositoryTest.php

Add a separate components for the creation of flightsignatures. Also refactor the code a bit

Extract flightsignature creation logic

---

Makefile
bin/doctrine
cli-config.php
src/Orm/Entity/PlanetCommodity.php
src/Orm/Entity/PlanetCommodityInterface.php

Also add missing entity for stu_planets_commodities

Replace deprecated orm cli

---

phpstan-baseline.neon
src/Module/Message/Lib/PrivateMessageSender.php
src/Orm/Entity/PrivateMessage.php
src/Orm/Entity/PrivateMessageInterface.php
src/Orm/Repository/ColonyShipRepairRepository.php
src/Orm/Repository/CrewTrainingRepository.php
src/Orm/Repository/ModuleQueueRepository.php
src/Orm/Repository/RepairTaskRepository.php
src/Orm/Repository/ShipyardShipQueueRepository.php
src/Orm/Repository/StationShipRepairRepository.php
tests/Module/Message/Lib/PrivateMessageSenderTest.php

This reverts commit bec44a81c591ce588baa871526639ec3884c66f6.

Revert "no flush on pm entanglement"
